Repository Do-it-Together-DoTo/DoTo_Front, pull requests merged in 2024-06, with the labels that each got.

#26 [Feat] Auth Page 기능 구현 및 My Page 기능 로직 구현 #25
  src/modal/FindPw.tsx
  src/modal/SignUp.tsx
  src/pages/mypage/BlockAccountPage.tsx
  src/pages/mypage/ChangePasswordPage.tsx
  src/pages/mypage/MydataPage.tsx
  src/pages/mypage/UpdateProfilePage.tsx
Labels: Feat✨

#27 Design: Store Page UI 구현
  .eslintcache
  public/svg/MyBlob.svg
  public/svg/Slider.svg
  public/svg/_NormalBadge.svg
  public/svg/_RareBadge.svg
  public/svg/coin.svg
  public/svg/egg.svg
  public/svg/magic_potion_1.svg
  public/svg/magic_potion_2.svg
  src/assets/svg/Coin.tsx
  src/assets/svg/Egg.tsx
  src/assets/svg/MagicPotion1.tsx
  src/assets/svg/MagicPotion2.tsx
  src/assets/svg/MyBlob.tsx
  src/assets/svg/NormalBadge.tsx
  src/assets/svg/RareBadge.tsx
  src/assets/svg/Slider.tsx
  src/assets/svg/index.ts
  src/components/common/category/CategoryConstant.ts
  src/components/store/InventoryCharacter.tsx
  src/components/store/InventoryItem.tsx
  src/components/store/ShopCharacter.tsx
  src/components/store/ShopItem.tsx
  src/components/store/StoreMainProfile.tsx
  src/modal/StoreDetailModal.tsx
  src/pages/store/InventoryCharacterPage.tsx
  src/pages/store/InventoryItemPage.tsx
  src/pages/store/InventoryPage.tsx
  src/pages/store/ShopCharacterPage.tsx
  src/pages/store/ShopItemPage.tsx
  src/pages/store/ShopPage.tsx
  src/router/Router.tsx
Labels: Design🎨

#34 33 feat 반응형에 필요한 설정 기능 구현
  src/hooks/useDeviceSize.tsx
  tailwind.config.js
Labels: Feat✨

#28 Feat: 커뮤니티 페이지 기능 구현
  public/svg/arrowLeftIcon.svg
  src/assets/svg/ArrowLeftIcon.tsx
  src/assets/svg/index.ts
  src/components/community/chatting/ChattingItem.tsx
  src/components/community/friend/FriendConstant.ts
  src/components/community/friend/FriendItem.tsx
  src/components/community/friend/FriendList.tsx
  src/components/community/friend/SearchFriends.tsx
  src/components/community/ranking/Timer.tsx
  src/dummy/Friend.ts
  src/modal/BettingModal.tsx
  src/modal/FriendModal.tsx
  src/pages/community/BettingPage.tsx
  src/pages/community/ChattingPage.tsx
  src/pages/community/ChattingRoomPage.tsx
  src/pages/community/FriendPage.tsx
Labels: Fix🐛, Design🎨

#35 #32 Feat: modal 연결 기능 구현
  .eslintcache
  index.html
  src/components/common/Modal.tsx
  src/components/common/ModalPortal.tsx
  src/hooks/.gitkeep
  src/hooks/useModal.tsx
  src/modal/StoreDetailModal.tsx
  src/pages/store/ShopCharacterPage.tsx
  tailwind.config.js
Labels: Feat✨
